### ISSUE TITLE
Liz Learn how to checkout a repo

### ISSUE THREAD

**Issue by lizargall** [themcclure/coffee#3]
Converting a note to an issue to see if that allows conversations to happen. It looks like comments can't happen on cards!

**Comment by lizargall** [comment]
Nice question @themcclure , for there are many things you can do in the code section, but none of them say check out! I shall have to google it!

**Comment by lizargall** [comment]
Differences between cloning and checking out a repository.
@themcclure  is this a universal use of the word cloning and checking out? https://stackoverflow.com/questions/7298598/what-is-the-difference-between-git-clone-and-checkout

**Comment by lizargall** [comment]
Have installed GitHub Desktop, added a file using Atom, modified a file using Atom. 

Is there anything else I should do with this learning?

**Comment by themcclure** [comment]
Checking out/in is the more general term... (the "kleenex") but I guess for git the on-brand phrase for it is "cloning".

Desktop should let you clone and edit, and the Atom editor will let you edit pretty much anything
